version: '3.7'

services:
  web:
    image: 8ct8pus/nginx-php-fpm-alpine:latest
    container_name: webp
    ports:
      - 80:80
      - 443:443
    environment:
      - DOMAIN=localhost
      - DOCUMENT_ROOT=/
    volumes:
      # development directory
      - ./src/:/var/www/site/
      # expose nginx logs to host
      - ./log/:/var/log/nginx/
      # expose nginx and php config to host
      - ./etc/:/docker/etc/
      # expose ssl certificates to host
      - ./ssl/:/etc/ssl/nginx/
